/*
  Complete Bangladesh administrative hierarchy: 8 divisions, 64 districts,
  and 495 upazilas. Names are sourced from
  @bangladeshi/bangladesh-address 2.1.0 and validated against the Bangladesh
  National Portal administrative-unit totals before this migration was built.
*/

IF OBJECT_ID(N'dbo.division', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.division (
    division_id BIGINT PRIMARY KEY,
    name NVARCHAR(100) NOT NULL
  );
END;

IF OBJECT_ID(N'dbo.district', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.district (
    district_id BIGINT PRIMARY KEY,
    division_id BIGINT NOT NULL REFERENCES dbo.division (division_id),
    name NVARCHAR(100) NOT NULL
  );
END;

IF OBJECT_ID(N'dbo.upazila', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.upazila (
    upazila_id BIGINT PRIMARY KEY,
    district_id BIGINT NOT NULL REFERENCES dbo.district (district_id),
    name NVARCHAR(100) NOT NULL
  );
END;

MERGE dbo.division AS target
USING (VALUES
  (1001, N'Barisal'),
  (1002, N'Chattogram'),
  (1003, N'Dhaka'),
  (1004, N'Khulna'),
  (1005, N'Mymensingh'),
  (1006, N'Rajshahi'),
  (1007, N'Rangpur'),
  (1008, N'Sylhet')
) AS source(division_id, name)
ON target.name = source.name
WHEN NOT MATCHED THEN
  INSERT (division_id, name) VALUES (source.division_id, source.name);

MERGE dbo.district AS target
USING (VALUES
  (2001, N'Barisal', N'Barguna'),
  (2002, N'Barisal', N'Barisal'),
  (2003, N'Barisal', N'Bhola'),
  (2004, N'Barisal', N'Jhalokati'),
  (2005, N'Barisal', N'Patuakhali'),
  (2006, N'Barisal', N'Pirojpur'),
  (2007, N'Chattogram', N'Bandarban'),
  (2008, N'Chattogram', N'Brahmanbaria'),
  (2009, N'Chattogram', N'Chandpur'),
  (2010, N'Chattogram', N'Chattogram'),
  (2011, N'Chattogram', N'Comilla'),
  (2012, N'Chattogram', N'Cox''s Bazar'),
  (2013, N'Chattogram', N'Feni'),
  (2014, N'Chattogram', N'Khagrachari'),
  (2015, N'Chattogram', N'Lakshmipur'),
  (2016, N'Chattogram', N'Noakhali'),
  (2017, N'Chattogram', N'Rangamati'),
  (2018, N'Dhaka', N'Dhaka'),
  (2019, N'Dhaka', N'Faridpur'),
  (2020, N'Dhaka', N'Gazipur'),
  (2021, N'Dhaka', N'Gopalganj'),
  (2022, N'Dhaka', N'Kishoreganj'),
  (2023, N'Dhaka', N'Madaripur'),
  (2024, N'Dhaka', N'Manikganj'),
  (2025, N'Dhaka', N'Munshiganj'),
  (2026, N'Dhaka', N'Narayanganj'),
  (2027, N'Dhaka', N'Narsingdi'),
  (2028, N'Dhaka', N'Rajbari'),
  (2029, N'Dhaka', N'Shariatpur'),
  (2030, N'Dhaka', N'Tangail'),
  (2031, N'Khulna', N'Bagerhat'),
  (2032, N'Khulna', N'Chuadanga'),
  (2033, N'Khulna', N'Jessore'),
  (2034, N'Khulna', N'Jhenaidah'),
  (2035, N'Khulna', N'Khulna'),
  (2036, N'Khulna', N'Kushtia'),
  (2037, N'Khulna', N'Magura'),
  (2038, N'Khulna', N'Meherpur'),
  (2039, N'Khulna', N'Narail'),
  (2040, N'Khulna', N'Satkhira'),
  (2041, N'Mymensingh', N'Jamalpur'),
  (2042, N'Mymensingh', N'Mymensingh'),
  (2043, N'Mymensingh', N'Netrokona'),
  (2044, N'Mymensingh', N'Sherpur'),
  (2045, N'Rajshahi', N'Bogra'),
  (2046, N'Rajshahi', N'Chapainawabganj'),
  (2047, N'Rajshahi', N'Joypurhat'),
  (2048, N'Rajshahi', N'Naogaon'),
  (2049, N'Rajshahi', N'Natore'),
  (2050, N'Rajshahi', N'Pabna'),
  (2051, N'Rajshahi', N'Rajshahi'),
  (2052, N'Rajshahi', N'Sirajganj'),
  (2053, N'Rangpur', N'Dinajpur'),
  (2054, N'Rangpur', N'Gaibandha'),
  (2055, N'Rangpur', N'Kurigram'),
  (2056, N'Rangpur', N'Lalmonirhat'),
  (2057, N'Rangpur', N'Nilphamari'),
  (2058, N'Rangpur', N'Panchagarh'),
  (2059, N'Rangpur', N'Rangpur'),
  (2060, N'Rangpur', N'Thakurgaon'),
  (2061, N'Sylhet', N'Habiganj'),
  (2062, N'Sylhet', N'Moulvibazar'),
  (2063, N'Sylhet', N'Sunamganj'),
  (2064, N'Sylhet', N'Sylhet')
) AS source(district_id, division_name, name)
ON target.name = source.name
 AND target.division_id = (SELECT division_id FROM dbo.division WHERE name=source.division_name)
WHEN NOT MATCHED THEN
  INSERT (district_id, division_id, name)
  VALUES (source.district_id,
          (SELECT division_id FROM dbo.division WHERE name=source.division_name),
          source.name);

MERGE dbo.upazila AS target
USING (VALUES
  (3001, N'Barisal', N'Barguna', N'Amtali'),
  (3002, N'Barisal', N'Barguna', N'Bamna'),
  (3003, N'Barisal', N'Barguna', N'Barguna Sadar'),
  (3004, N'Barisal', N'Barguna', N'Betagi'),
  (3005, N'Barisal', N'Barguna', N'Patharghata'),
  (3006, N'Barisal', N'Barguna', N'Taltali'),
  (3007, N'Barisal', N'Barisal', N'Agailjhara'),
  (3008, N'Barisal', N'Barisal', N'Babuganj'),
  (3009, N'Barisal', N'Barisal', N'Bakerganj'),
  (3010, N'Barisal', N'Barisal', N'Banaripara'),
  (3011, N'Barisal', N'Barisal', N'Barisal Sadar'),
  (3012, N'Barisal', N'Barisal', N'Gaurnadi'),
  (3013, N'Barisal', N'Barisal', N'Hizla'),
  (3014, N'Barisal', N'Barisal', N'Mehendiganj'),
  (3015, N'Barisal', N'Barisal', N'Muladi'),
  (3016, N'Barisal', N'Barisal', N'Wazirpur'),
  (3017, N'Barisal', N'Bhola', N'Bhola Sadar'),
  (3018, N'Barisal', N'Bhola', N'Burhanuddin'),
  (3019, N'Barisal', N'Bhola', N'Char Fasson'),
  (3020, N'Barisal', N'Bhola', N'Daulatkhan'),
  (3021, N'Barisal', N'Bhola', N'Lalmohan'),
  (3022, N'Barisal', N'Bhola', N'Manpura'),
  (3023, N'Barisal', N'Bhola', N'Tazumuddin'),
  (3024, N'Barisal', N'Jhalokati', N'Jhalokati Sadar'),
  (3025, N'Barisal', N'Jhalokati', N'Kathalia'),
  (3026, N'Barisal', N'Jhalokati', N'Nalchity'),
  (3027, N'Barisal', N'Jhalokati', N'Rajapur'),
  (3028, N'Barisal', N'Patuakhali', N'Bauphal'),
  (3029, N'Barisal', N'Patuakhali', N'Dashmina'),
  (3030, N'Barisal', N'Patuakhali', N'Dumki'),
  (3031, N'Barisal', N'Patuakhali', N'Galachipa'),
  (3032, N'Barisal', N'Patuakhali', N'Kalapara'),
  (3033, N'Barisal', N'Patuakhali', N'Mirzaganj'),
  (3034, N'Barisal', N'Patuakhali', N'Patuakhali Sadar'),
  (3035, N'Barisal', N'Patuakhali', N'Rangabali'),
  (3036, N'Barisal', N'Pirojpur', N'Bhandaria'),
  (3037, N'Barisal', N'Pirojpur', N'Kaukhali'),
  (3038, N'Barisal', N'Pirojpur', N'Mathbaria'),
  (3039, N'Barisal', N'Pirojpur', N'Nazirpur'),
  (3040, N'Barisal', N'Pirojpur', N'Nesarabad'),
  (3041, N'Barisal', N'Pirojpur', N'Pirojpur Sadar'),
  (3042, N'Barisal', N'Pirojpur', N'Zianagar'),
  (3043, N'Chattogram', N'Bandarban', N'Ali kadam'),
  (3044, N'Chattogram', N'Bandarban', N'Bandarban Sadar'),
  (3045, N'Chattogram', N'Bandarban', N'Lama'),
  (3046, N'Chattogram', N'Bandarban', N'Naikhongchhari'),
  (3047, N'Chattogram', N'Bandarban', N'Rowangchhari'),
  (3048, N'Chattogram', N'Bandarban', N'Ruma'),
  (3049, N'Chattogram', N'Bandarban', N'Thanchi'),
  (3050, N'Chattogram', N'Brahmanbaria', N'Akhaura'),
  (3051, N'Chattogram', N'Brahmanbaria', N'Ashuganj'),
  (3052, N'Chattogram', N'Brahmanbaria', N'Bancharampur'),
  (3053, N'Chattogram', N'Brahmanbaria', N'Bijoynagar'),
  (3054, N'Chattogram', N'Brahmanbaria', N'Brahmanbaria Sadar'),
  (3055, N'Chattogram', N'Brahmanbaria', N'Kasba'),
  (3056, N'Chattogram', N'Brahmanbaria', N'Nabinagar'),
  (3057, N'Chattogram', N'Brahmanbaria', N'Nasirnagar'),
  (3058, N'Chattogram', N'Brahmanbaria', N'Sarail'),
  (3059, N'Chattogram', N'Brahmanbaria', N'Shahbazpur Town'),
  (3060, N'Chattogram', N'Chandpur', N'Chandpur Sadar'),
  (3061, N'Chattogram', N'Chandpur', N'Faridganj'),
  (3062, N'Chattogram', N'Chandpur', N'Haimchar'),
  (3063, N'Chattogram', N'Chandpur', N'Haziganj'),
  (3064, N'Chattogram', N'Chandpur', N'Kachua'),
  (3065, N'Chattogram', N'Chandpur', N'Matlab Dakkhin'),
  (3066, N'Chattogram', N'Chandpur', N'Matlab Uttar'),
  (3067, N'Chattogram', N'Chandpur', N'Shahrasti'),
  (3068, N'Chattogram', N'Chattogram', N'Anwara'),
  (3069, N'Chattogram', N'Chattogram', N'Banshkhali'),
  (3070, N'Chattogram', N'Chattogram', N'Boalkhali'),
  (3071, N'Chattogram', N'Chattogram', N'Chandanaish'),
  (3072, N'Chattogram', N'Chattogram', N'Fatikchhari'),
  (3073, N'Chattogram', N'Chattogram', N'Hathazari'),
  (3074, N'Chattogram', N'Chattogram', N'Lohagara'),
  (3075, N'Chattogram', N'Chattogram', N'Mirsharai'),
  (3076, N'Chattogram', N'Chattogram', N'Patiya'),
  (3077, N'Chattogram', N'Chattogram', N'Rangunia'),
  (3078, N'Chattogram', N'Chattogram', N'Raozan'),
  (3079, N'Chattogram', N'Chattogram', N'Sandwip'),
  (3080, N'Chattogram', N'Chattogram', N'Satkania'),
  (3081, N'Chattogram', N'Chattogram', N'Sitakunda'),
  (3082, N'Chattogram', N'Comilla', N'Barura'),
  (3083, N'Chattogram', N'Comilla', N'Brahmanpara'),
  (3084, N'Chattogram', N'Comilla', N'Burichong'),
  (3085, N'Chattogram', N'Comilla', N'Chandina'),
  (3086, N'Chattogram', N'Comilla', N'Chauddagram'),
  (3087, N'Chattogram', N'Comilla', N'Comilla Sadar'),
  (3088, N'Chattogram', N'Comilla', N'Comilla Sadar South'),
  (3089, N'Chattogram', N'Comilla', N'Daudkandi'),
  (3090, N'Chattogram', N'Comilla', N'Debidwar'),
  (3091, N'Chattogram', N'Comilla', N'Homna'),
  (3092, N'Chattogram', N'Comilla', N'Laksam'),
  (3093, N'Chattogram', N'Comilla', N'Meghna'),
  (3094, N'Chattogram', N'Comilla', N'Monohorgonj'),
  (3095, N'Chattogram', N'Comilla', N'Muradnagar'),
  (3096, N'Chattogram', N'Comilla', N'Nangalkot'),
  (3097, N'Chattogram', N'Comilla', N'Titas'),
  (3098, N'Chattogram', N'Cox''s Bazar', N'Chakaria'),
  (3099, N'Chattogram', N'Cox''s Bazar', N'Cox''s Bazar Sadar'),
  (3100, N'Chattogram', N'Cox''s Bazar', N'Eidgaon'),
  (3101, N'Chattogram', N'Cox''s Bazar', N'Kutubdia'),
  (3102, N'Chattogram', N'Cox''s Bazar', N'Maheshkhali'),
  (3103, N'Chattogram', N'Cox''s Bazar', N'Pekua'),
  (3104, N'Chattogram', N'Cox''s Bazar', N'Ramu'),
  (3105, N'Chattogram', N'Cox''s Bazar', N'Teknaf'),
  (3106, N'Chattogram', N'Cox''s Bazar', N'Ukhia'),
  (3107, N'Chattogram', N'Feni', N'Chagalnaiya'),
  (3108, N'Chattogram', N'Feni', N'Daganbhyan'),
  (3109, N'Chattogram', N'Feni', N'Feni Sadar'),
  (3110, N'Chattogram', N'Feni', N'Fhulgazi'),
  (3111, N'Chattogram', N'Feni', N'Parshuram'),
  (3112, N'Chattogram', N'Feni', N'Sonagazi'),
  (3113, N'Chattogram', N'Khagrachari', N'Dighinala'),
  (3114, N'Chattogram', N'Khagrachari', N'Khagrachhari'),
  (3115, N'Chattogram', N'Khagrachari', N'Lakshmichhari'),
  (3116, N'Chattogram', N'Khagrachari', N'Mahalchhari'),
  (3117, N'Chattogram', N'Khagrachari', N'Manikchhari'),
  (3118, N'Chattogram', N'Khagrachari', N'Matiranga'),
  (3119, N'Chattogram', N'Khagrachari', N'Panchhari'),
  (3120, N'Chattogram', N'Khagrachari', N'Ramgarh'),
  (3121, N'Chattogram', N'Lakshmipur', N'Komol Nagar'),
  (3122, N'Chattogram', N'Lakshmipur', N'Lakshmipur Sadar'),
  (3123, N'Chattogram', N'Lakshmipur', N'Raipur'),
  (3124, N'Chattogram', N'Lakshmipur', N'Ramganj'),
  (3125, N'Chattogram', N'Lakshmipur', N'Ramgati'),
  (3126, N'Chattogram', N'Noakhali', N'Begumganj'),
  (3127, N'Chattogram', N'Noakhali', N'Chatkhil'),
  (3128, N'Chattogram', N'Noakhali', N'Companyganj'),
  (3129, N'Chattogram', N'Noakhali', N'Hatia'),
  (3130, N'Chattogram', N'Noakhali', N'Kobirhat'),
  (3131, N'Chattogram', N'Noakhali', N'Noakhali Sadar'),
  (3132, N'Chattogram', N'Noakhali', N'Shenbag'),
  (3133, N'Chattogram', N'Noakhali', N'Sonaimuri'),
  (3134, N'Chattogram', N'Noakhali', N'Suborno Char'),
  (3135, N'Chattogram', N'Rangamati', N'Bagaichhari'),
  (3136, N'Chattogram', N'Rangamati', N'Barkal'),
  (3137, N'Chattogram', N'Rangamati', N'Belaichhari'),
  (3138, N'Chattogram', N'Rangamati', N'Juraichhari'),
  (3139, N'Chattogram', N'Rangamati', N'Kaptai'),
  (3140, N'Chattogram', N'Rangamati', N'Kaukhali'),
  (3141, N'Chattogram', N'Rangamati', N'Langadu'),
  (3142, N'Chattogram', N'Rangamati', N'Nannerchar'),
  (3143, N'Chattogram', N'Rangamati', N'Rajasthali'),
  (3144, N'Chattogram', N'Rangamati', N'Rangamati Sadar'),
  (3145, N'Dhaka', N'Dhaka', N'Dhamrai'),
  (3146, N'Dhaka', N'Dhaka', N'Dohar'),
  (3147, N'Dhaka', N'Dhaka', N'Keraniganj'),
  (3148, N'Dhaka', N'Dhaka', N'Nawabganj'),
  (3149, N'Dhaka', N'Dhaka', N'Savar'),
  (3150, N'Dhaka', N'Faridpur', N'Alfadanga'),
  (3151, N'Dhaka', N'Faridpur', N'Bhanga'),
  (3152, N'Dhaka', N'Faridpur', N'Boalmari'),
  (3153, N'Dhaka', N'Faridpur', N'Charbhadrasan'),
  (3154, N'Dhaka', N'Faridpur', N'Faridpur Sadar'),
  (3155, N'Dhaka', N'Faridpur', N'Madhukhali'),
  (3156, N'Dhaka', N'Faridpur', N'Nagarkanda'),
  (3157, N'Dhaka', N'Faridpur', N'Sadarpur'),
  (3158, N'Dhaka', N'Faridpur', N'Shaltha'),
  (3159, N'Dhaka', N'Gazipur', N'Gazipur Sadar-Joydebpur'),
  (3160, N'Dhaka', N'Gazipur', N'Kaliakior'),
  (3161, N'Dhaka', N'Gazipur', N'Kaliganj'),
  (3162, N'Dhaka', N'Gazipur', N'Kapasia'),
  (3163, N'Dhaka', N'Gazipur', N'Sripur'),
  (3164, N'Dhaka', N'Gazipur', N'Tongi'),
  (3165, N'Dhaka', N'Gopalganj', N'Gopalganj Sadar'),
  (3166, N'Dhaka', N'Gopalganj', N'Kashiani'),
  (3167, N'Dhaka', N'Gopalganj', N'Kotalipara'),
  (3168, N'Dhaka', N'Gopalganj', N'Muksudpur'),
  (3169, N'Dhaka', N'Gopalganj', N'Tungipara'),
  (3170, N'Dhaka', N'Kishoreganj', N'Astagram'),
  (3171, N'Dhaka', N'Kishoreganj', N'Bajitpur'),
  (3172, N'Dhaka', N'Kishoreganj', N'Bhairab'),
  (3173, N'Dhaka', N'Kishoreganj', N'Hossainpur'),
  (3174, N'Dhaka', N'Kishoreganj', N'Itna'),
  (3175, N'Dhaka', N'Kishoreganj', N'Karimganj'),
  (3176, N'Dhaka', N'Kishoreganj', N'Katiadi'),
  (3177, N'Dhaka', N'Kishoreganj', N'Kishoreganj Sadar'),
  (3178, N'Dhaka', N'Kishoreganj', N'Kuliarchar'),
  (3179, N'Dhaka', N'Kishoreganj', N'Mithamain'),
  (3180, N'Dhaka', N'Kishoreganj', N'Nikli'),
  (3181, N'Dhaka', N'Kishoreganj', N'Pakundia'),
  (3182, N'Dhaka', N'Kishoreganj', N'Tarail'),
  (3183, N'Dhaka', N'Madaripur', N'Dasar'),
  (3184, N'Dhaka', N'Madaripur', N'Kalkini'),
  (3185, N'Dhaka', N'Madaripur', N'Madaripur Sadar'),
  (3186, N'Dhaka', N'Madaripur', N'Rajoir'),
  (3187, N'Dhaka', N'Madaripur', N'Shibchar'),
  (3188, N'Dhaka', N'Manikganj', N'Daulatpur'),
  (3189, N'Dhaka', N'Manikganj', N'Ghior'),
  (3190, N'Dhaka', N'Manikganj', N'Harirampur'),
  (3191, N'Dhaka', N'Manikganj', N'Manikganj Sadar'),
  (3192, N'Dhaka', N'Manikganj', N'Saturia'),
  (3193, N'Dhaka', N'Manikganj', N'Shibalaya'),
  (3194, N'Dhaka', N'Manikganj', N'Singair'),
  (3195, N'Dhaka', N'Munshiganj', N'Gazaria'),
  (3196, N'Dhaka', N'Munshiganj', N'Lohajang'),
  (3197, N'Dhaka', N'Munshiganj', N'Munshiganj Sadar'),
  (3198, N'Dhaka', N'Munshiganj', N'Sirajdikhan'),
  (3199, N'Dhaka', N'Munshiganj', N'Sreenagar'),
  (3200, N'Dhaka', N'Munshiganj', N'Tongibari'),
  (3201, N'Dhaka', N'Narayanganj', N'Araihazar'),
  (3202, N'Dhaka', N'Narayanganj', N'Bandar'),
  (3203, N'Dhaka', N'Narayanganj', N'Naryanganj Sadar'),
  (3204, N'Dhaka', N'Narayanganj', N'Rupganj'),
  (3205, N'Dhaka', N'Narayanganj', N'Siddirgonj'),
  (3206, N'Dhaka', N'Narayanganj', N'Sonargaon'),
  (3207, N'Dhaka', N'Narsingdi', N'Belabo'),
  (3208, N'Dhaka', N'Narsingdi', N'Monohardi'),
  (3209, N'Dhaka', N'Narsingdi', N'Narsingdi Sadar'),
  (3210, N'Dhaka', N'Narsingdi', N'Palash'),
  (3211, N'Dhaka', N'Narsingdi', N'Raipura'),
  (3212, N'Dhaka', N'Narsingdi', N'Shibpur'),
  (3213, N'Dhaka', N'Rajbari', N'Baliakandi'),
  (3214, N'Dhaka', N'Rajbari', N'Goalandaghat'),
  (3215, N'Dhaka', N'Rajbari', N'Kalukhali'),
  (3216, N'Dhaka', N'Rajbari', N'Pangsha'),
  (3217, N'Dhaka', N'Rajbari', N'Rajbari Sadar'),
  (3218, N'Dhaka', N'Shariatpur', N'Bhedarganj'),
  (3219, N'Dhaka', N'Shariatpur', N'Damudya'),
  (3220, N'Dhaka', N'Shariatpur', N'Gosairhat'),
  (3221, N'Dhaka', N'Shariatpur', N'Jajira'),
  (3222, N'Dhaka', N'Shariatpur', N'Naria'),
  (3223, N'Dhaka', N'Shariatpur', N'Shariatpur Sadar'),
  (3224, N'Dhaka', N'Tangail', N'Basail'),
  (3225, N'Dhaka', N'Tangail', N'Bhuapur'),
  (3226, N'Dhaka', N'Tangail', N'Delduar'),
  (3227, N'Dhaka', N'Tangail', N'Dhanbari'),
  (3228, N'Dhaka', N'Tangail', N'Ghatail'),
  (3229, N'Dhaka', N'Tangail', N'Gopalpur'),
  (3230, N'Dhaka', N'Tangail', N'Kalihati'),
  (3231, N'Dhaka', N'Tangail', N'Madhupur'),
  (3232, N'Dhaka', N'Tangail', N'Mirzapur'),
  (3233, N'Dhaka', N'Tangail', N'Nagarpur'),
  (3234, N'Dhaka', N'Tangail', N'Sakhipur'),
  (3235, N'Dhaka', N'Tangail', N'Tangail Sadar'),
  (3236, N'Khulna', N'Bagerhat', N'Bagerhat Sadar'),
  (3237, N'Khulna', N'Bagerhat', N'Chitalmari'),
  (3238, N'Khulna', N'Bagerhat', N'Fakirhat'),
  (3239, N'Khulna', N'Bagerhat', N'Kachua'),
  (3240, N'Khulna', N'Bagerhat', N'Mollahat'),
  (3241, N'Khulna', N'Bagerhat', N'Mongla'),
  (3242, N'Khulna', N'Bagerhat', N'Morrelganj'),
  (3243, N'Khulna', N'Bagerhat', N'Rampal'),
  (3244, N'Khulna', N'Bagerhat', N'Sarankhola'),
  (3245, N'Khulna', N'Chuadanga', N'Alamdanga'),
  (3246, N'Khulna', N'Chuadanga', N'Chuadanga Sadar'),
  (3247, N'Khulna', N'Chuadanga', N'Damurhuda'),
  (3248, N'Khulna', N'Chuadanga', N'Jibannagar'),
  (3249, N'Khulna', N'Jessore', N'Abhaynagar'),
  (3250, N'Khulna', N'Jessore', N'Bagherpara'),
  (3251, N'Khulna', N'Jessore', N'Chaugachha'),
  (3252, N'Khulna', N'Jessore', N'Jessore Sadar'),
  (3253, N'Khulna', N'Jessore', N'Jhikargachha'),
  (3254, N'Khulna', N'Jessore', N'Keshabpur'),
  (3255, N'Khulna', N'Jessore', N'Manirampur'),
  (3256, N'Khulna', N'Jessore', N'Sharsha'),
  (3257, N'Khulna', N'Jhenaidah', N'Harinakunda'),
  (3258, N'Khulna', N'Jhenaidah', N'Jhenaidah Sadar'),
  (3259, N'Khulna', N'Jhenaidah', N'Kaliganj'),
  (3260, N'Khulna', N'Jhenaidah', N'Kotchandpur'),
  (3261, N'Khulna', N'Jhenaidah', N'Maheshpur'),
  (3262, N'Khulna', N'Jhenaidah', N'Shailkupa'),
  (3263, N'Khulna', N'Khulna', N'Batiaghata'),
  (3264, N'Khulna', N'Khulna', N'Dacope'),
  (3265, N'Khulna', N'Khulna', N'Dighalia'),
  (3266, N'Khulna', N'Khulna', N'Dumuria'),
  (3267, N'Khulna', N'Khulna', N'Koyra'),
  (3268, N'Khulna', N'Khulna', N'Paikgachha'),
  (3269, N'Khulna', N'Khulna', N'Phultala'),
  (3270, N'Khulna', N'Khulna', N'Rupsa'),
  (3271, N'Khulna', N'Khulna', N'Terokhada'),
  (3272, N'Khulna', N'Kushtia', N'Bheramara'),
  (3273, N'Khulna', N'Kushtia', N'Daulatpur'),
  (3274, N'Khulna', N'Kushtia', N'Khoksa'),
  (3275, N'Khulna', N'Kushtia', N'Kumarkhali'),
  (3276, N'Khulna', N'Kushtia', N'Kushtia Sadar'),
  (3277, N'Khulna', N'Kushtia', N'Mirpur'),
  (3278, N'Khulna', N'Magura', N'Magura Sadar'),
  (3279, N'Khulna', N'Magura', N'Mohammadpur'),
  (3280, N'Khulna', N'Magura', N'Shalikha'),
  (3281, N'Khulna', N'Magura', N'Sreepur'),
  (3282, N'Khulna', N'Meherpur', N'Gangni'),
  (3283, N'Khulna', N'Meherpur', N'Meherpur Sadar'),
  (3284, N'Khulna', N'Meherpur', N'Mujibnagar'),
  (3285, N'Khulna', N'Narail', N'Kalia'),
  (3286, N'Khulna', N'Narail', N'Lohagara'),
  (3287, N'Khulna', N'Narail', N'Narail Sadar'),
  (3288, N'Khulna', N'Satkhira', N'Assasuni'),
  (3289, N'Khulna', N'Satkhira', N'Debhata'),
  (3290, N'Khulna', N'Satkhira', N'Kalaroa'),
  (3291, N'Khulna', N'Satkhira', N'Kaliganj'),
  (3292, N'Khulna', N'Satkhira', N'Satkhira Sadar'),
  (3293, N'Khulna', N'Satkhira', N'Shyamnagar'),
  (3294, N'Khulna', N'Satkhira', N'Tala'),
  (3295, N'Mymensingh', N'Jamalpur', N'Baksiganj'),
  (3296, N'Mymensingh', N'Jamalpur', N'Dewanganj'),
  (3297, N'Mymensingh', N'Jamalpur', N'Islampur'),
  (3298, N'Mymensingh', N'Jamalpur', N'Jamalpur Sadar'),
  (3299, N'Mymensingh', N'Jamalpur', N'Madarganj'),
  (3300, N'Mymensingh', N'Jamalpur', N'Melandaha'),
  (3301, N'Mymensingh', N'Jamalpur', N'Narundi Police I.C'),
  (3302, N'Mymensingh', N'Jamalpur', N'Sarishabari'),
  (3303, N'Mymensingh', N'Mymensingh', N'Bhaluka'),
  (3304, N'Mymensingh', N'Mymensingh', N'Dhobaura'),
  (3305, N'Mymensingh', N'Mymensingh', N'Fulbaria'),
  (3306, N'Mymensingh', N'Mymensingh', N'Gaffargaon'),
  (3307, N'Mymensingh', N'Mymensingh', N'Gauripur'),
  (3308, N'Mymensingh', N'Mymensingh', N'Haluaghat'),
  (3309, N'Mymensingh', N'Mymensingh', N'Ishwarganj'),
  (3310, N'Mymensingh', N'Mymensingh', N'Muktagachha'),
  (3311, N'Mymensingh', N'Mymensingh', N'Mymensingh Sadar'),
  (3312, N'Mymensingh', N'Mymensingh', N'Nandail'),
  (3313, N'Mymensingh', N'Mymensingh', N'Phulpur'),
  (3314, N'Mymensingh', N'Mymensingh', N'Tarakanda'),
  (3315, N'Mymensingh', N'Mymensingh', N'Trishal'),
  (3316, N'Mymensingh', N'Netrokona', N'Atpara'),
  (3317, N'Mymensingh', N'Netrokona', N'Barhatta'),
  (3318, N'Mymensingh', N'Netrokona', N'Durgapur'),
  (3319, N'Mymensingh', N'Netrokona', N'Kalmakanda'),
  (3320, N'Mymensingh', N'Netrokona', N'Kendua'),
  (3321, N'Mymensingh', N'Netrokona', N'Khaliajuri'),
  (3322, N'Mymensingh', N'Netrokona', N'Madan'),
  (3323, N'Mymensingh', N'Netrokona', N'Mohanganj'),
  (3324, N'Mymensingh', N'Netrokona', N'Netrokona Sadar'),
  (3325, N'Mymensingh', N'Netrokona', N'Purbadhala'),
  (3326, N'Mymensingh', N'Sherpur', N'Jhenaigati'),
  (3327, N'Mymensingh', N'Sherpur', N'Nakla'),
  (3328, N'Mymensingh', N'Sherpur', N'Nalitabari'),
  (3329, N'Mymensingh', N'Sherpur', N'Sherpur Sadar'),
  (3330, N'Mymensingh', N'Sherpur', N'Sreebardi'),
  (3331, N'Rajshahi', N'Bogra', N'Adamdighi'),
  (3332, N'Rajshahi', N'Bogra', N'Bogra Sadar'),
  (3333, N'Rajshahi', N'Bogra', N'Dhunat'),
  (3334, N'Rajshahi', N'Bogra', N'Dhupchanchia'),
  (3335, N'Rajshahi', N'Bogra', N'Gabtali'),
  (3336, N'Rajshahi', N'Bogra', N'Kahaloo'),
  (3337, N'Rajshahi', N'Bogra', N'Nandigram'),
  (3338, N'Rajshahi', N'Bogra', N'Sahajanpur'),
  (3339, N'Rajshahi', N'Bogra', N'Sariakandi'),
  (3340, N'Rajshahi', N'Bogra', N'Sherpur'),
  (3341, N'Rajshahi', N'Bogra', N'Shibganj'),
  (3342, N'Rajshahi', N'Bogra', N'Sonatala'),
  (3343, N'Rajshahi', N'Chapainawabganj', N'Bholahat'),
  (3344, N'Rajshahi', N'Chapainawabganj', N'Chapainawabganj Sadar'),
  (3345, N'Rajshahi', N'Chapainawabganj', N'Gomastapur'),
  (3346, N'Rajshahi', N'Chapainawabganj', N'Nachole'),
  (3347, N'Rajshahi', N'Chapainawabganj', N'Shibganj'),
  (3348, N'Rajshahi', N'Joypurhat', N'Akkelpur'),
  (3349, N'Rajshahi', N'Joypurhat', N'Joypurhat Sadar'),
  (3350, N'Rajshahi', N'Joypurhat', N'Kalai'),
  (3351, N'Rajshahi', N'Joypurhat', N'Khetlal'),
  (3352, N'Rajshahi', N'Joypurhat', N'Panchbibi'),
  (3353, N'Rajshahi', N'Naogaon', N'Atrai'),
  (3354, N'Rajshahi', N'Naogaon', N'Badalgachhi'),
  (3355, N'Rajshahi', N'Naogaon', N'Dhamoirhat'),
  (3356, N'Rajshahi', N'Naogaon', N'Manda'),
  (3357, N'Rajshahi', N'Naogaon', N'Mohadevpur'),
  (3358, N'Rajshahi', N'Naogaon', N'Naogaon Sadar'),
  (3359, N'Rajshahi', N'Naogaon', N'Niamatpur'),
  (3360, N'Rajshahi', N'Naogaon', N'Patnitala'),
  (3361, N'Rajshahi', N'Naogaon', N'Porsha'),
  (3362, N'Rajshahi', N'Naogaon', N'Raninagar'),
  (3363, N'Rajshahi', N'Naogaon', N'Sapahar'),
  (3364, N'Rajshahi', N'Natore', N'Bagatipara'),
  (3365, N'Rajshahi', N'Natore', N'Baraigram'),
  (3366, N'Rajshahi', N'Natore', N'Gurudaspur'),
  (3367, N'Rajshahi', N'Natore', N'Lalpur'),
  (3368, N'Rajshahi', N'Natore', N'Natore Sadar'),
  (3369, N'Rajshahi', N'Natore', N'Singra'),
  (3370, N'Rajshahi', N'Pabna', N'Atgharia'),
  (3371, N'Rajshahi', N'Pabna', N'Bera'),
  (3372, N'Rajshahi', N'Pabna', N'Bhangura'),
  (3373, N'Rajshahi', N'Pabna', N'Chatmohar'),
  (3374, N'Rajshahi', N'Pabna', N'Faridpur'),
  (3375, N'Rajshahi', N'Pabna', N'Ishwardi'),
  (3376, N'Rajshahi', N'Pabna', N'Pabna Sadar'),
  (3377, N'Rajshahi', N'Pabna', N'Santhia'),
  (3378, N'Rajshahi', N'Pabna', N'Sujanagar'),
  (3379, N'Rajshahi', N'Rajshahi', N'Bagha'),
  (3380, N'Rajshahi', N'Rajshahi', N'Bagmara'),
  (3381, N'Rajshahi', N'Rajshahi', N'Charghat'),
  (3382, N'Rajshahi', N'Rajshahi', N'Durgapur'),
  (3383, N'Rajshahi', N'Rajshahi', N'Godagari'),
  (3384, N'Rajshahi', N'Rajshahi', N'Mohanpur'),
  (3385, N'Rajshahi', N'Rajshahi', N'Paba'),
  (3386, N'Rajshahi', N'Rajshahi', N'Puthia'),
  (3387, N'Rajshahi', N'Rajshahi', N'Tanore'),
  (3388, N'Rajshahi', N'Sirajganj', N'Belkuchi'),
  (3389, N'Rajshahi', N'Sirajganj', N'Chauhali'),
  (3390, N'Rajshahi', N'Sirajganj', N'Kamarkhanda'),
  (3391, N'Rajshahi', N'Sirajganj', N'Kazipur'),
  (3392, N'Rajshahi', N'Sirajganj', N'Raiganj'),
  (3393, N'Rajshahi', N'Sirajganj', N'Shahjadpur'),
  (3394, N'Rajshahi', N'Sirajganj', N'Sirajganj Sadar'),
  (3395, N'Rajshahi', N'Sirajganj', N'Tarash'),
  (3396, N'Rajshahi', N'Sirajganj', N'Ullahpara'),
  (3397, N'Rangpur', N'Dinajpur', N'Biral'),
  (3398, N'Rangpur', N'Dinajpur', N'Birampur'),
  (3399, N'Rangpur', N'Dinajpur', N'Birganj'),
  (3400, N'Rangpur', N'Dinajpur', N'Bochaganj'),
  (3401, N'Rangpur', N'Dinajpur', N'Chirirbandar'),
  (3402, N'Rangpur', N'Dinajpur', N'Dinajpur Sadar'),
  (3403, N'Rangpur', N'Dinajpur', N'Ghoraghat'),
  (3404, N'Rangpur', N'Dinajpur', N'Hakimpur'),
  (3405, N'Rangpur', N'Dinajpur', N'Kaharole'),
  (3406, N'Rangpur', N'Dinajpur', N'Khansama'),
  (3407, N'Rangpur', N'Dinajpur', N'Nawabganj'),
  (3408, N'Rangpur', N'Dinajpur', N'Parbatipur'),
  (3409, N'Rangpur', N'Dinajpur', N'Phulbari'),
  (3410, N'Rangpur', N'Gaibandha', N'Fulchhari'),
  (3411, N'Rangpur', N'Gaibandha', N'Gaibandha Sadar'),
  (3412, N'Rangpur', N'Gaibandha', N'Gobindaganj'),
  (3413, N'Rangpur', N'Gaibandha', N'Palashbari'),
  (3414, N'Rangpur', N'Gaibandha', N'Sadullapur'),
  (3415, N'Rangpur', N'Gaibandha', N'Saghata'),
  (3416, N'Rangpur', N'Gaibandha', N'Sundarganj'),
  (3417, N'Rangpur', N'Kurigram', N'Bhurungamari'),
  (3418, N'Rangpur', N'Kurigram', N'Char Rajibpur'),
  (3419, N'Rangpur', N'Kurigram', N'Chilmari'),
  (3420, N'Rangpur', N'Kurigram', N'Kurigram Sadar'),
  (3421, N'Rangpur', N'Kurigram', N'Nageshwari'),
  (3422, N'Rangpur', N'Kurigram', N'Phulbari'),
  (3423, N'Rangpur', N'Kurigram', N'Rajarhat'),
  (3424, N'Rangpur', N'Kurigram', N'Rowmari'),
  (3425, N'Rangpur', N'Kurigram', N'Ulipur'),
  (3426, N'Rangpur', N'Lalmonirhat', N'Aditmari'),
  (3427, N'Rangpur', N'Lalmonirhat', N'Hatibandha'),
  (3428, N'Rangpur', N'Lalmonirhat', N'Kaliganj'),
  (3429, N'Rangpur', N'Lalmonirhat', N'Lalmonirhat Sadar'),
  (3430, N'Rangpur', N'Lalmonirhat', N'Patgram'),
  (3431, N'Rangpur', N'Nilphamari', N'Dimla'),
  (3432, N'Rangpur', N'Nilphamari', N'Domar'),
  (3433, N'Rangpur', N'Nilphamari', N'Jaldhaka'),
  (3434, N'Rangpur', N'Nilphamari', N'Kishoreganj'),
  (3435, N'Rangpur', N'Nilphamari', N'Nilphamari Sadar'),
  (3436, N'Rangpur', N'Nilphamari', N'Saidpur'),
  (3437, N'Rangpur', N'Panchagarh', N'Atwari'),
  (3438, N'Rangpur', N'Panchagarh', N'Boda'),
  (3439, N'Rangpur', N'Panchagarh', N'Debiganj'),
  (3440, N'Rangpur', N'Panchagarh', N'Panchagarh Sadar'),
  (3441, N'Rangpur', N'Panchagarh', N'Tetulia'),
  (3442, N'Rangpur', N'Rangpur', N'Badarganj'),
  (3443, N'Rangpur', N'Rangpur', N'Gangachara'),
  (3444, N'Rangpur', N'Rangpur', N'Kaunia'),
  (3445, N'Rangpur', N'Rangpur', N'Mithapukur'),
  (3446, N'Rangpur', N'Rangpur', N'Pirgachha'),
  (3447, N'Rangpur', N'Rangpur', N'Pirganj'),
  (3448, N'Rangpur', N'Rangpur', N'Rangpur Sadar'),
  (3449, N'Rangpur', N'Rangpur', N'Taraganj'),
  (3450, N'Rangpur', N'Thakurgaon', N'Baliadangi'),
  (3451, N'Rangpur', N'Thakurgaon', N'Haripur'),
  (3452, N'Rangpur', N'Thakurgaon', N'Pirganj'),
  (3453, N'Rangpur', N'Thakurgaon', N'Ranisankail'),
  (3454, N'Rangpur', N'Thakurgaon', N'Thakurgaon Sadar'),
  (3455, N'Sylhet', N'Habiganj', N'Ajmiriganj'),
  (3456, N'Sylhet', N'Habiganj', N'Bahubal'),
  (3457, N'Sylhet', N'Habiganj', N'Baniachang'),
  (3458, N'Sylhet', N'Habiganj', N'Chunarughat'),
  (3459, N'Sylhet', N'Habiganj', N'Habiganj Sadar'),
  (3460, N'Sylhet', N'Habiganj', N'Lakhai'),
  (3461, N'Sylhet', N'Habiganj', N'Madhabpur'),
  (3462, N'Sylhet', N'Habiganj', N'Nabiganj'),
  (3463, N'Sylhet', N'Habiganj', N'Shaistagonj'),
  (3464, N'Sylhet', N'Moulvibazar', N'Barlekha'),
  (3465, N'Sylhet', N'Moulvibazar', N'Juri'),
  (3466, N'Sylhet', N'Moulvibazar', N'Kamalganj'),
  (3467, N'Sylhet', N'Moulvibazar', N'Kulaura'),
  (3468, N'Sylhet', N'Moulvibazar', N'Moulvibazar Sadar'),
  (3469, N'Sylhet', N'Moulvibazar', N'Rajnagar'),
  (3470, N'Sylhet', N'Moulvibazar', N'Sreemangal'),
  (3471, N'Sylhet', N'Sunamganj', N'Bishwamvarpur'),
  (3472, N'Sylhet', N'Sunamganj', N'Chhatak'),
  (3473, N'Sylhet', N'Sunamganj', N'Derai'),
  (3474, N'Sylhet', N'Sunamganj', N'Dharampasha'),
  (3475, N'Sylhet', N'Sunamganj', N'Dowarabazar'),
  (3476, N'Sylhet', N'Sunamganj', N'Jagannathpur'),
  (3477, N'Sylhet', N'Sunamganj', N'Jamalganj'),
  (3478, N'Sylhet', N'Sunamganj', N'Madhyanagar'),
  (3479, N'Sylhet', N'Sunamganj', N'Shanthiganj'),
  (3480, N'Sylhet', N'Sunamganj', N'Sulla'),
  (3481, N'Sylhet', N'Sunamganj', N'Sunamganj Sadar'),
  (3482, N'Sylhet', N'Sunamganj', N'Tahirpur'),
  (3483, N'Sylhet', N'Sylhet', N'Balaganj'),
  (3484, N'Sylhet', N'Sylhet', N'Beanibazar'),
  (3485, N'Sylhet', N'Sylhet', N'Bishwanath'),
  (3486, N'Sylhet', N'Sylhet', N'Companiganj'),
  (3487, N'Sylhet', N'Sylhet', N'Dakshin Surma'),
  (3488, N'Sylhet', N'Sylhet', N'Fenchuganj'),
  (3489, N'Sylhet', N'Sylhet', N'Golapganj'),
  (3490, N'Sylhet', N'Sylhet', N'Gowainghat'),
  (3491, N'Sylhet', N'Sylhet', N'Jaintiapur'),
  (3492, N'Sylhet', N'Sylhet', N'Kanaighat'),
  (3493, N'Sylhet', N'Sylhet', N'Osmaninagar'),
  (3494, N'Sylhet', N'Sylhet', N'Sylhet Sadar'),
  (3495, N'Sylhet', N'Sylhet', N'Zakiganj')
) AS source(upazila_id, division_name, district_name, name)
ON target.name = source.name
 AND target.district_id = (
   SELECT d.district_id
   FROM dbo.district d
   JOIN dbo.division v ON v.division_id=d.division_id
   WHERE d.name=source.district_name AND v.name=source.division_name
 )
WHEN NOT MATCHED THEN
  INSERT (upazila_id, district_id, name)
  VALUES (source.upazila_id,
          (SELECT d.district_id
           FROM dbo.district d
           JOIN dbo.division v ON v.division_id=d.division_id
           WHERE d.name=source.district_name AND v.name=source.division_name),
          source.name);
